# Generated by Django 4.2.8 on 2026-02-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_number',
            field=models.CharField(default='TEMP', help_text='Employee ID - Unique identifier', max_length=50, unique=True),
        ),
    ]
