# Generated by Django 4.2.8 on 2026-02-23 09:14

from django.db import migrations, models
import uuid


def generate_temp_employee_numbers(apps, schema_editor):
    """Generate unique temporary employee numbers for existing users"""
    User = apps.get_model('users', 'User')
    for user in User.objects.filter(employee_number='TEMP'):
        # Generate a unique temp ID
        user.employee_number = f'TEMP-{str(uuid.uuid4())[:8].upper()}'
        user.save(update_fields=['employee_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        # First add the field without unique constraint
        migrations.AddField(
            model_name='user',
            name='employee_number',
            field=models.CharField(default='TEMP', help_text='Employee ID - Unique identifier', max_length=50),
        ),
        # Generate unique values for existing records
        migrations.RunPython(generate_temp_employee_numbers, migrations.RunPython.noop),
        # Then add the unique constraint
        migrations.AlterField(
            model_name='user',
            name='employee_number',
            field=models.CharField(help_text='Employee ID - Unique identifier', max_length=50, unique=True),
        ),
    ]
