# Generated by Django 4.2.8 on 2026-02-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_picture_alter_user_employee_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('TEACHER', 'Teacher'), ('HEADTEACHER', 'Headteacher'), ('DEPUTY_HEAD', 'Deputy Headteacher'), ('SOCIAL_OFFICER', 'Social Services Officer'), ('ACADEMIC_MANAGER', 'Academic Manager'), ('HEAD_OF_OPS', 'Head of Operations'), ('DIRECTOR', 'Director')], default='TEACHER', max_length=50),
        ),
    ]
