# Generated by Django 4.2.8 on 2026-02-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='category',
            field=models.CharField(blank=True, choices=[('LOWER_PRIMARY', 'Lower Primary'), ('UPPER_PRIMARY', 'Upper Primary'), ('SECONDARY', 'Secondary'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
