databases:
  - name: school-management-db
    databaseName: school_db
    user: school_user
    plan: free

services:
  - type: web
    name: school-management-api
    runtime: python
    plan: free
    rootDirectory: school_management
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: school-management-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
