# Generated by Django 4.2.8 on 2026-02-24 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0001_initial'),
        ('schools', '0001_initial'),
        ('students', '0002_alter_student_unique_together_student_child_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('assessment_type', models.CharField(choices=[('TEST', 'Test'), ('QUIZ', 'Quiz'), ('EXAM', 'Exam'), ('ASSIGNMENT', 'Assignment'), ('PROJECT', 'Project'), ('PRACTICAL', 'Practical')], max_length=50)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight in final grade calculation', max_digits=5)),
                ('date_conducted', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='schools.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.term')),
            ],
            options={
                'ordering': ['-date_conducted'],
                'unique_together': {('name', 'subject', 'grade', 'term')},
            },
        ),
        migrations.CreateModel(
            name='TermGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_possible_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_letter', models.CharField(max_length=2)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_grades', to='academics.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_grades', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_grades', to='academics.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_grades', to='academics.term')),
            ],
            options={
                'ordering': ['-calculated_at'],
                'unique_together': {('student', 'subject', 'term', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6)),
                ('remarks', models.TextField(blank=True, help_text="Teacher's comments/remarks")),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='assessments.assessment')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_entered', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.student')),
            ],
            options={
                'ordering': ['-entered_at'],
                'unique_together': {('assessment', 'student')},
            },
        ),
    ]
