# Generated by Django 4.2.8 on 2026-02-23 09:14

from django.db import migrations, models
import uuid


def generate_temp_child_ids(apps, schema_editor):
    """Generate unique temporary child IDs for existing students"""
    Student = apps.get_model('students', 'Student')
    for student in Student.objects.filter(child_id='TEMP'):
        # Generate a unique temp ID
        student.child_id = f'TEMP-{str(uuid.uuid4())[:8].upper()}'
        student.save(update_fields=['child_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        # Remove old unique constraint
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        # Add child_id field
        migrations.AddField(
            model_name='student',
            name='child_id',
            field=models.CharField(default='TEMP', help_text='Child ID/CHL - Unique identifier', max_length=50),
        ),
        # Generate unique child_ids for existing students
        migrations.RunPython(generate_temp_child_ids, migrations.RunPython.noop),
        # Make admission_number optional
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        # Add new unique constraint on (school, child_id)
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('school', 'child_id')},
        ),
    ]
