# Generated by Django 4.2.8 on 2026-02-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='student',
            name='child_id',
            field=models.CharField(default='TEMP', help_text='Child ID/CHL - Unique identifier', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('school', 'child_id')},
        ),
    ]
