# Generated by Django 4.2.8 on 2026-02-25 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0002_alter_student_unique_together_student_child_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.stream'),
        ),
    ]
